Mars receipt library
elixir-europe/MARS pull request #52
Opened 2024-10-15 11:54 UTC by Pedram-A-Keyvani

The `mars-receipt` library handles all MARS receipt stuff.  
It contains `isamodel`, `marsmodel` and the receipt provider to build a MARS receipt from the mapped repository receipt.

All the related models are removed from `isajson-ena` and `isajson-biosamples` services.
The `isajson-biosamples` receipt implementation on `isajson-ena` is removed from the place. The output of the `isajson-ena` service now is MARS receipt, not the modified ISA-JSON.

2024-10-23 13:26 UTC, Pedram-A-Keyvani commented
#46  closed

2024-11-04 08:50 UTC, kdp-cloud requested changes
The build step is fixed but when running the container, it complains that it can't find `/app.jar`.

2024-11-04 08:53 UTC, kdp-cloud commented on repository-services/isajson-biosamples/Dockerfile
> +WORKDIR /app
Since you are already in /app, the entrypoint should be `ENTRYPOINT ["java", "-jar", "app.jar"]` (without the /)

2024-11-04 08:54 UTC, kdp-cloud commented on repository-services/isajson-ena/Dockerfile
> +WORKDIR /app
Same comment as https://github.com/elixir-europe/MARS/pull/52/files#r1827386760

2024-11-04 08:57 UTC, kdp-cloud commented
Also, could you adjust the docker-compose.yml file please.

2024-11-04 16:04 UTC, Pedram-A-Keyvani commented
> The build step is fixed but when running the container, it complains that it can't find `/app.jar`.

Did you try to run the container from `repository-services/` directory?

2024-11-05 07:57 UTC, kdp-cloud commented
> > The build step is fixed but when running the container, it complains that it can't find `/app.jar`.
> 
> Did you try to run the container from `repository-services/` directory?

I think it has nothing to do with it.
It's because in your Dockerfile you have a directive:
`ENTRYPOINT ["java", "-jar", "/app.jar"]` which does not exist because you copied the jar file to the `/app` folder in your container (see [comment above](https://github.com/elixir-europe/MARS/pull/52#discussion_r1827386760)).

So you directive should be `ENTRYPOINT ["java", "-jar", "/app/app.jar"]` but since you also have the `WORKDIR /app`, you can simply do:
`ENTRYPOINT ["java", "-jar", "app.jar"]`

I tested it and it like this and it works. I can push the changes later on.

2024-11-05 08:18 UTC, kdp-cloud approved these changes

2024-11-05 10:55 UTC, dipayan1985 approved these changes
Looks good to me.

2024-11-05 11:17 UTC, merged